(()=>{'use strict';
const CONTRACT='system_control_center.json';
const state={contract:null,overview:{},processes:[],services:[],kpis:[],profiles:null,pending:null};
const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const fmtBytes=n=>{n=Number(n);if(!Number.isFinite(n))return '—';const u=['B','KB','MB','GB','TB'];let i=0;while(n>=1024&&i<4){n/=1024;i++}return `${n.toFixed(i?1:0)} ${u[i]}`};
const statusClass=s=>['healthy','running','active','ok'].includes(String(s).toLowerCase())?'ok':['failed','error','dead'].includes(String(s).toLowerCase())?'bad':['warning','degraded','paused'].includes(String(s).toLowerCase())?'warn':'';
async function get(path){try{const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw Error(r.status);return await r.json()}catch{return null}}
function capability(key){return !!state.contract?.capabilities?.[key]}
async function load(){state.contract=await get(CONTRACT)||{capabilities:{}};state.overview=await get('/api/system/overview')||{};state.processes=await get('/api/system/processes')||[];state.services=await get('/api/system/services')||[];state.kpis=await get('/api/system/kpis')||[];if(!Array.isArray(state.processes))state.processes=state.processes.processes||[];if(!Array.isArray(state.services))state.services=state.services.services||[];if(!Array.isArray(state.kpis))state.kpis=state.kpis.kpis||[];state.profiles=await get('desktop_profiles.json');render();}
function backend(){return state.overview.source||state.kpis.find(x=>x.source)?.source||'web-browser'}
function render(){
 $('#backendBadge').textContent=`Backend: ${backend()}`;
 const score=state.overview.health_score??state.kpis.find(x=>x.id==='health.score')?.value;$('#healthScore').textContent=Number.isFinite(Number(score))?Math.round(Number(score)):'—';$('#healthHeadline').textContent=state.overview.health_label||'System telemetry available';$('#healthDetail').textContent=state.overview.detail||'Metrics are sourced from the available backend. Unknown values are never fabricated.';
 const cards=(state.kpis.length?state.kpis.slice(0,8):[{id:'cpu',label:'CPU',value:'—',unit:'%',status:'unknown',source:'unavailable'},{id:'memory',label:'Memory',value:'—',unit:'%',status:'unknown',source:'unavailable'},{id:'storage',label:'Storage',value:'—',unit:'%',status:'unknown',source:'unavailable'},{id:'network',label:'Network',value:'—',unit:'status',status:'unknown',source:'unavailable'}]);
 $('#kpiGrid').innerHTML=cards.map(k=>`<article class="kpi"><small>${esc(k.label||k.id)}</small><b>${esc(k.value)} ${esc(k.unit||'')}</b><span class="status ${statusClass(k.status)}">${esc(k.status||'unknown')} · ${esc(k.source||'unknown')}</span></article>`).join('');
 $('#componentGrid').innerHTML=(state.overview.components||[{label:'Koronos Kernel',status:'unknown',source:'unavailable'},{label:'ISA / N-bit Runtime',status:'unknown',source:'unavailable'},{label:'Aurora Graphics',status:'unknown',source:'unavailable'},{label:'Cognitive Plane',status:'unknown',source:'unavailable'}]).map(x=>`<div class="component"><b>${esc(x.label)}</b><span class="status ${statusClass(x.status)}">${esc(x.status||'unknown')}</span><small class="muted"> ${esc(x.source||'unknown')}</small></div>`).join('');
 renderProcesses();renderServices();renderPerformance();renderProfiles();renderSettings();
}
function renderProcesses(){const q=($('#processFilter')?.value||'').toLowerCase();const rows=state.processes.filter(p=>JSON.stringify(p).toLowerCase().includes(q));$('#processSummary').textContent=`${rows.length} process${rows.length===1?'':'es'} · ${capability('process_manage')?'management enabled':'read-only browser mode'}`;$('#processRows').innerHTML=rows.map(p=>`<tr><td>${esc(p.pid)}</td><td><b>${esc(p.name)}</b><br><small class="muted">${esc(p.command||'')}</small></td><td>${esc(p.user)}</td><td>${p.cpu_percent==null?'—':Number(p.cpu_percent).toFixed(1)+'%'}</td><td>${p.memory_bytes!=null?fmtBytes(p.memory_bytes):(p.memory_percent==null?'—':p.memory_percent+'%')}</td><td>${esc(p.state||'unknown')}</td><td><span class="status ${statusClass(p.health)}">${esc(p.health||'unknown')}</span></td><td><button data-process-action="process.stop-request" data-pid="${esc(p.pid)}" ${capability('process_manage')?'':'disabled'}>Stop</button></td></tr>`).join('')||'<tr><td colspan="8" class="empty">No process data is available.</td></tr>'}
function renderServices(){const q=($('#serviceFilter')?.value||'').toLowerCase();const rows=state.services.filter(s=>JSON.stringify(s).toLowerCase().includes(q));$('#serviceSummary').textContent=`${rows.length} service${rows.length===1?'':'s'} · ${capability('service_manage')?'management enabled':'read-only browser mode'}`;$('#serviceRows').innerHTML=rows.map(s=>`<tr><td><b>${esc(s.name||s.id)}</b></td><td>${esc(s.description)}</td><td><span class="status ${statusClass(s.state)}">${esc(s.state||'unknown')}</span></td><td>${esc(s.startup||'unknown')}</td><td>${esc(s.pid??'—')}</td><td><span class="status ${statusClass(s.health)}">${esc(s.health||'unknown')}</span></td><td><div class="power-actions"><button data-service-action="service.start-request" data-service="${esc(s.id)}" ${s.can_start&&capability('service_manage')?'':'disabled'}>Start</button><button data-service-action="service.stop-request" data-service="${esc(s.id)}" ${s.can_stop&&capability('service_manage')?'':'disabled'}>Stop</button><button data-service-action="service.restart-request" data-service="${esc(s.id)}" ${s.can_restart&&capability('service_manage')?'':'disabled'}>Restart</button></div></td></tr>`).join('')||'<tr><td colspan="7" class="empty">No service data is available.</td></tr>'}
function renderPerformance(){$('#performanceGrid').innerHTML=state.kpis.map(k=>`<article class="metric"><small>${esc(k.label||k.id)}</small><h3>${esc(k.value)} ${esc(k.unit||'')}</h3><span class="status ${statusClass(k.status)}">${esc(k.status||'unknown')}</span><p>${esc(k.detail||'Source: '+(k.source||'unknown'))}</p><small>${esc(k.timestamp||'no timestamp')} · confidence ${esc(k.confidence??'unknown')}</small></article>`).join('')||'<div class="empty">No KPI telemetry is available.</div>'}
function renderProfiles(){if(!state.profiles)return;$('#desktopProfile').innerHTML=state.profiles.profiles.map(p=>`<option value="${esc(p.id)}">${esc(p.title)}</option>`).join('');$('#desktopProfile').value=localStorage.getItem('chimera.desktop.profile')||state.profiles.default;$('#sessionCards').innerHTML=state.profiles.profiles.slice(0,9).map(p=>`<div class="component"><b>${esc(p.title)}</b><small>${esc(p.description)}</small><br><span class="status">${esc(p.mode)}</span></div>`).join('')}
function renderSettings(){const s=JSON.parse(localStorage.getItem('chimera.control.settings')||'{}');['theme','taskbar','power','terminal','security'].forEach(k=>{const el=$('#'+k);if(el)el.value=s[k]||el.value});$('#notifications').checked=s.notifications!==false}
function saveSettings(){const s={theme:$('#theme').value,taskbar:$('#taskbar').value,power:$('#power').value,terminal:$('#terminal').value,security:$('#security').value,notifications:$('#notifications').checked};localStorage.setItem('chimera.control.settings',JSON.stringify(s));localStorage.setItem('chimera.desktop.profile',$('#desktopProfile').value);$('#settingsStatus').textContent='Preferences saved locally.';window.opener?.postMessage({type:'chimera-settings-changed'},'*')}
async function requestAction(action,target){if(!capability(action.includes('process')?'process_manage':action.includes('service')?'service_manage':'session_power_control')){alert('This operation requires an authorized native/session backend. The current Web UI is read-only.');return}state.pending={action,target};$('#confirmText').textContent=`Request ${action} for ${target}. This may affect the running system.`;$('#confirmDialog').showModal()}
async function executePending(){const p=state.pending;if(!p)return;try{const r=await fetch('/api/system/action',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(p)});const out=await r.json();if(!r.ok||out.ok===false)throw Error(out.error||`HTTP ${r.status}`);$('#settingsStatus').textContent='Action completed.';await load()}catch(e){alert(`Management request failed: ${e.message}`)}finally{state.pending=null}}
document.addEventListener('click',e=>{const n=e.target.closest('.nav');if(n){document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));n.classList.add('active');document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));$('#'+n.dataset.tab).classList.add('active')}const p=e.target.closest('[data-process-action]');if(p)requestAction(p.dataset.processAction,p.dataset.pid);const s=e.target.closest('[data-service-action]');if(s)requestAction(s.dataset.serviceAction,s.dataset.service);});
$('#confirmAction').addEventListener('click',e=>{e.preventDefault();$('#confirmDialog').close();executePending()});$('#refreshBtn').onclick=load;$('#saveSettings').onclick=saveSettings;$('#processFilter').oninput=renderProcesses;$('#serviceFilter').oninput=renderServices;$('#desktopProfile').onchange=()=>{localStorage.setItem('chimera.desktop.profile',$('#desktopProfile').value);document.body.dataset.desktop=$('#desktopProfile').value};
load();setInterval(load,Number(state.contract?.refresh_ms)||5000);
})();
