#include "chimera/desktop.hpp"
#include <algorithm>
#include <stdexcept>
#include <cmath>
namespace chimera {
static const std::vector<std::string> standard={"firmware / platform discovery","memory and register initialization","ISA/runtime initialization","security and trust initialization","storage/filesystem discovery","Koronos kernel initialization","network/runtime services","desktop session preparation"};
SpitfireBootProgress::SpitfireBootProgress():SpitfireBootProgress(standard){} SpitfireBootProgress::SpitfireBootProgress(std::vector<std::string>s):stages_(std::move(s)),done_(stages_.size(),false){if(stages_.empty())throw std::invalid_argument("boot stages");}
int SpitfireBootProgress::complete(const std::string&s){auto it=std::find(stages_.begin(),stages_.end(),s);if(it==stages_.end())throw std::invalid_argument("unknown boot stage");done_[it-stages_.begin()]=true;return percent();} int SpitfireBootProgress::percent()const{size_t n=0;for(bool x:done_)n+=x;return (int)std::lround(100.0*n/done_.size());} bool SpitfireBootProgress::complete_all()const{return std::all_of(done_.begin(),done_.end(),[](bool x){return x;});}const std::vector<std::string>&SpitfireBootProgress::stages()const{return stages_;}
int DesktopLoadingProgress::set(int x){p_=std::clamp(x,0,100);return p_;}int DesktopLoadingProgress::percent()const{return p_;}int DesktopLoadingProgress::sweep_degrees()const{return p_*360/100;}bool DesktopLoadingProgress::complete()const{return p_==100;}
int BootDesktopProgressCoordinator::boot_percent()const{return boot_.percent();}bool BootDesktopProgressCoordinator::boot_complete()const{return boot_.complete_all();}bool BootDesktopProgressCoordinator::desktop_started()const{return boot_complete();}void BootDesktopProgressCoordinator::complete_boot_stage(const std::string&s){boot_.complete(s);}void BootDesktopProgressCoordinator::complete_all_boot(){for(const auto&s:boot_.stages())boot_.complete(s);}void BootDesktopProgressCoordinator::set_desktop_percent(int p){if(!desktop_started())throw std::logic_error("desktop before boot");desktop_.set(p);}int BootDesktopProgressCoordinator::desktop_percent()const{return desktop_.percent();}int BootDesktopProgressCoordinator::desktop_sweep_degrees()const{return desktop_.sweep_degrees();}bool BootDesktopProgressCoordinator::startup_complete()const{return boot_complete()&&desktop_.complete();}
}
